- name: Demo on using copyFile
  hosts: all
  tasks:
    - name: 
      ansible.builtin.copy:
       src: systemd.txt
       dest: /home/centos
    - name: 
      ansible.builtin.fetch:
       src: /home/centos
       dest: /home/centos/Demo/New/Ansible
       flat: false