- name: Demo on using facts
  hosts: all
  tasks:
    - name: This is a frontend task
      ansible.builtin.debug:
       msg: Installing Frontend
      tags: frontend
    - name: Starting frontend
      ansible.builtin.debug:
       msg: Starting frontend
       tags: frontend
    - name: This is a user task
      ansible.builtin.debug:
       msg: Installing user
       tags: user
    - name: Starting user
      ansible.builtin.debug:
       msg: Starting user
       tags: user
    - name: This is a cart task
      ansible.builtin.debug:
       msg: Installing cart
       tags: cart