- name: Demo on using Shell module
  hosts: all
  tasks:
    - name: Demo on using Shell module
      ansible.builtin.shell: uptime
      register: OUT
    - name: Demo on using Shell module
      ansible.builtin.debug:
       msg: "{{OUT}}"