- name: Play1
  hosts: all
  vars:
   URL: play.google.com     # Global variable
  tasks:
    - name: Printing Hello form play1
      vars:
       URL: task.gmail.com    # Local Variable
      ansible.builtin.debug:
       msg: "{{ URL }}"