- name: Play1
  hosts: all
  vars:
   URL: play.google.com     # Global variable
  vars_files:   #From external file
   - dev-vars.yaml
  tasks:
    - name: Printing Hello form play1
      vars:
       URL: task.gmail.com    # Local Variable
      ansible.builtin.debug:
       msg: "{{ URL }}"
- name: Play2
  hosts: prod
  tasks:
    - name: Printing Hello form play2
      ansible.builtin.debug:
       msg: "{{ Var }}"  # cmd line arg ->> -e Var=I_am_from_Prod_env
       # Precedence of variable
       # From externalfile - commandline - Local - Global