- name: Check the errors
  hosts: all
  tasks:
    - name: checking the Java is installed or not
      ansible.builtin.shell: ps -ef | grep java |grep -v grep
      register: OUT
      ignore_errors: yes

    - name: Starting Tomcat
      ansible.builtin.debug:
       msg: Starting Tomcat
      