- name: Demo on using priveledge user
  hosts: all
  become: yes
  tasks:
    - name: checking the user id
      ansible.builtin.shell: id
      register: OUT
    - name: printing the user details
      ansible.builtin.debug:
       msg: "{{OUT.stdout}}"
